image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-default

stages:
  - test
  - build

test:pytest-pylint:
  stage: test
  script:
    - poetry lock --no-update
    - poetry install
    - poetry run pytest -vv
    - poetry run pylint --disable=R,fixme opsideployclientagent
    - poetry run flake8 opsideployclientagent

build:linux-pyinstaller:
  stage: build
  script:
    - poetry lock --no-update
    - poetry install
    - poetry run opsi-dev-cli -l info pyinstaller build
    - ./dist/opsi-deploy-client-agent --version
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-cli -l info binary push dist/opsi-deploy-client-agent --prerelease="$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-cli -l info binary push dist/opsi-deploy-client-agent'
