image: docker.uib.gmbh/opsi/dev/pybuilder:latest

stages:
  - build

.get-opsi-server: &get-opsi-server |
  url=$(git remote -v | grep fetch | cut -f2 | sed s'#/opsi-deploy-client-agent.git.*#/opsi-server.git#')
  GIT_TERMINAL_PROMPT=0 git clone $url
  cp -a opsi-server/opsi-server_data/etc /etc/opsi

build:linux-pyinstaller:
  stage: build
  script:
    - *get-opsi-server
    - poetry install
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - ./dist/opsi-deploy-client-agent --version
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-tool -l info --binary-push dist/opsi-deploy-client-agent "$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-tool -l info --binary-push dist/opsi-deploy-client-agent'
  artifacts:
    name: 'deploy-linux-pyinstaller'
    paths:
      - dist/opsi-deploy-client-agent
    expire_in: 2 day
