image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-3.10

stages:
  - test
  - build

.get-opsi-server: &get-opsi-server |
  url=$(git remote -v | grep fetch | cut -f2 | sed s'#/opsi-deploy-client-agent.git.*#/opsi-server.git#')
  GIT_TERMINAL_PROMPT=0 git clone $url
  cp -a opsi-server/opsi-server_data/etc /etc/opsi

test:pytest-pylint:
  stage: test
  script:
    - poetry lock --no-update
    - poetry install
    # Conflicts with smbclient package
    - rm .venv/bin/smbclient.py || true
    - poetry run pylint --disable=R,fixme opsideployclientagent
    - poetry run flake8 opsideployclientagent

build:linux-pyinstaller:
  stage: build
  script:
    - *get-opsi-server
    - poetry lock --no-update
    - poetry install
    # Conflicts with smbclient package
    - rm .venv/bin/smbclient.py || true
    - poetry run opsi-dev-cli -l info pyinstaller build
    - ./dist/opsi-deploy-client-agent --version
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-cli -l info binary push dist/opsi-deploy-client-agent --prerelease="$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-cli -l info binary push dist/opsi-deploy-client-agent'
