image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-3.11

stages:
  - test
  - build


test:pytest-pylint:
  stage: test
  script:
    - poetry lock --no-update
    - poetry install
    # Conflicts with smbclient package
    - rm .venv/bin/smbclient.py || true
    - poetry run pytest -vv
    - poetry run ruff opsideployclientagent tests

build:linux-pyinstaller:
  stage: build
  script:
    - poetry lock --no-update
    - poetry install
    # Conflicts with smbclient package
    - rm .venv/bin/smbclient.py || true
    - poetry run opsi-dev-cli -l info pyinstaller build
    - ./dist/opsi-deploy-client-agent --version
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-cli -l info binary push dist/opsi-deploy-client-agent --prerelease="$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-cli -l info binary push dist/opsi-deploy-client-agent'
