[project]
name = "opsi-deploy-client-agent"
version = "4.3.2.1"
description = "tool to deploy the opsi-client-agent on linux, windows and macOS clients"
readme = "README.md"
license = "AGPL-3.0-only"
requires-python = ">=3.11,<3.14"
dependencies = [
	"python-opsi-common>=4.3.29,<4.4",
	"paramiko>=3.4",
	"impacket>=0.11",
	"smbprotocol>=1.13",
	"gssapi>=1.8",
	"pydantic-core>=2.20",
	"annotated-types>=0.7",
]

[[project.authors]]
name = "uib GmbH"
email = "info@uib.de"

[[project.maintainers]]
name = "uib GmbH"
email = "info@uib.de"

[dependency-groups]
dev = ["ruff>=0.5", "pytest>=8.2", "pyinstaller>=6.9", "mypy>=1.10"]

[project.urls]
Homepage = "https://www.opsi.org"

[project.scripts]
opsi-deploy-client-agent = "opsideployclientagent.__main__:main"

[tool.uv]
extra-index-url = ["https://pypi.uib.gmbh/simple"]
index-strategy = "unsafe-best-match"
package = true

[tool.ruff]
line-length = 140

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
follow_imports = "silent"
incremental = false

[tool.ruff.format]
indent-style = "tab"

[tool.setuptools.packages.find]
include = ["opsideployclientagent", "opsideployclientagent.*"]
